services:
  - type: web
    name: 501laravel
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: 501laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: 501laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: 501laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: 501laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: 501laravel-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: 501laravel-db
    databaseName: laravel_db
    plan: free
